autoUpdate: true
initialized: true
initializedAt: '2026-03-12 13:46:29.484974'
language: zh
logLevel: info
packsDir: /root/.openclaw/workspace/packs
version: 1.1.0
workspacePath: /root/.openclaw/workspace/workspace
